SERVER:
    ENV: dev
    BIND:
        ADDRESS :  0.0.0.0
        PORT: 4200
    WORKERS: uvicorn.workers.UvicornWorker
    CAPTURE: false
    THREADS_PER_CORE: 16
    LOG:
        DIR: ${LOG_DIR}
        LEVEL: ${LOG_LEVEL}

DATABASES: {}

FASTAPI:
  CONFIG: {}

